# Generated by Django 4.1.5 on 2023-02-06 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bankingApp', '0004_transactions_date_alter_transactions_account'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Transactions',
            new_name='Transaction',
        ),
    ]
