# Generated by Django 4.1.5 on 2023-03-13 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankingApp', '0011_alter_transaction_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='balance',
            field=models.TextField(default=''),
        ),
    ]
