# Generated by Django 4.1.5 on 2023-02-05 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bankingApp', '0002_account_transactions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transactions',
            old_name='condition',
            new_name='type',
        ),
    ]
