# Generated by Django 4.1.5 on 2023-03-13 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankingApp', '0009_alter_transaction_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.BinaryField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='balance',
            field=models.BinaryField(default=b''),
        ),
    ]
