# Generated by Django 4.1.5 on 2023-03-13 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankingApp', '0015_alter_transaction_amount_alter_user_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='balance',
            field=models.TextField(default=''),
        ),
    ]
