# Generated by Django 4.1.5 on 2023-03-13 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankingApp', '0016_alter_transaction_amount_alter_user_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='balance',
            field=models.TextField(default=b''),
        ),
    ]
